[project]
name = "torch_numopt"
version = "0.2.1"
description = "Classic numerical optimizaton methods for Pytorch neural networks"
readme = "README.md"
authors = [
    { name = "eugenioLR", email = "eugeniolorente0@gmail.com" }
]

requires-python = ">=3.10"
dependencies = [
    "torch"
]
